### ISSUE TITLE
Setup test configuration and add tests

### ISSUE THREAD

**Issue by mikerourke** [mikerourke/toggl-to-clockify#3]
## Goal
Setup Jest and write tests

## Tasks

- [x] Install and configure `jest` and `ts-jest`
- [ ] Setup Toggl test account and seed
- [ ] Setup Clockify test account and seed

**Comment by mikerourke** [comment]
Installed and configured Jest on #4.
